Added German dialogTemplates
project-alice-powered-by-snips/ProjectAliceModules pull request #39
Opened 2019-10-07 20:57 UTC by JonahKr

I added german dialogTeplates for:

- RedQueen
- Wikipedia

_and corrected a one word spelling mistake in en.json from RedQueen_

2019-10-08 05:34 UTC, Psychokiller1888 requested changes
Thank you for your contribution! Your files are indented with 4 spaces instead of tabs, please update and I'll merge

2019-10-08 18:41 UTC, JonahKr commented
@Psychokiller1888  Why does the CI fail this build? I only added changed/added 3 files.

2019-10-08 18:47 UTC, JonahKr reviewed
should be ready

2019-10-09 12:25 UTC, Psychokiller1888 approved these changes

2019-10-09 12:25 UTC, merged